[package]
name = "space_game"
version = "0.1.0"
authors = ["Jayshua Nelson <me@jayshuanelson.com>"]

[dependencies]
dcpu16_emulator = {path = "../dcpu16_emulator"}
glium = "*"
glutin = "0.12.0"
rand = "0.4.2"